### ISSUE TITLE
有剑气轮播图

### ISSUE THREAD

**Issue by ayaotz233** [haxibiao/youjianqi#13]
已经试做了四份轮播图，交给蔡志刚进行测试；
这一块应该是由管理员先审核文章，之后进行推荐，推荐的同时制作合适的Banner，直接从文章中提取图片或者封面图不够美观。

**Comment by caizhigang1997** [comment]
前期可以把处理好的图片做好发给我，直接加入数据库。后面需求频繁的话，做一个定制首页轮播图的逻辑。

**Comment by ayaotz233** [comment]
一共需要八个；
目前网站轮播图选取规则应该是文章最后一张图；有些内容还不太合适的（比如漫画之类的竖版图）
还存在 新的选择上首页的文章 顶掉之前的文章 的问题，正常来讲应该是可以选8篇的吧？现在好像只可以显示三四篇的样子；

**Comment by ayaotz233** [comment]
问答页面轮播图也需要修改~

**Comment by ivanzhang2** [comment]
问题已过期，现在问题同步ainicheng
