### ISSUE TITLE
有剑气网站图片显示问题

### ISSUE THREAD

**Issue by ayaotz233** [haxibiao/youjianqi#14]
写文章插入图片，对图片的长宽有限制，发布后显示的图片会被强行拉伸，影响阅读体验，建议修改为图片按比例缩放；

**Comment by ayaotz233** [comment]
设置主要图片时，应为横版图片，如果选择的是竖版图，我觉得应该有裁剪显示的功能...

**Comment by xiaoyunhuai** [comment]
现在应该可以了
