### ISSUE TITLE
后端代码添加

### ISSUE THREAD

**Issue by ayaotz233** [haxibiao/youjianqi#5]
需要后台添加两端代码，统计使用；
1. 新版统计代码获取 
此代码同时适用于PC端、移动端的页面，以异步加载形式进行加载，数据更准确、加载速度更快。请将此代码复制并粘贴到您要跟踪的每个网页中。
<script>

var _hmt = _hmt || [];

(function() {

  var hm = document.createElement("script");

  hm.src = "https://hm.baidu.com/hm.js?744e648d217d1f7252a22a593b1cb230";

  var s = document.getElementsByTagName("script")[0]; 

  s.parentNode.insertBefore(hm, s);

})();

</script>

**Comment by ayaotz233** [comment]
后端负责这个，今天最好可以搞定，明天开始统计

**Comment by caizhigang1997** [comment]
已经添加

**Comment by ayaotz233** [comment]
没有问题了，可以正常统计
