### ISSUE TITLE
有剑气网页主页跳转问题

### ISSUE THREAD

**Issue by ayaotz233** [haxibiao/youjianqi#6]
点击logo图标不可跳转到首页；
发现和首页是一页吗？
是否有必要去掉发现这一选项或者添加新的页面进去？

**Comment by caizhigang1997** [comment]
1.已经加入点击logo跳转到首页.
2.目前系统上面的发现和首页是一样的.
3.最后一个问题,可以说说你的看法吗?

**Comment by ayaotz233** [comment]
修改推荐排序，已沟通过

**Comment by ivanzhang2** [comment]
请把沟通结果 总结简述出来，这个issue关闭之前，要知道具体怎么做了

**Comment by ayaotz233** [comment]
未登录状态下，根据热门（浏览量）在首页推荐文章，登陆后根据用户自己关注的专题的作者，在首页进行推荐。

**Comment by caizhigang1997** [comment]
完成爬虫工作后会开始做

**Comment by ivanzhang2** [comment]
问题已过期，现在问题同步ainicheng
