### ISSUE TITLE
后端代码添加（2）

### ISSUE THREAD

**Issue by ayaotz233** [haxibiao/youjianqi#7]
2.HTML标签验证
将以下代码添加到您的网站首页HTML代码的<head>标签与</head>标签之间，完成操作后请点击“验证”按钮。

<meta name="baidu-site-verification" content="RmUVga2bBl" />

**Comment by ivanzhang2** [comment]
这个可以参考之前网站给编辑SEO用户身份提供添加SEO标签，统计代码的功能，方便今后SEO身份用户随时添加其他验证代码和统计代码

**Comment by caizhigang1997** [comment]
已添加

**Comment by ayaotz233** [comment]
没有问题了，可以正常统计
