### ISSUE TITLE
添加外链图片的ui设计

### ISSUE THREAD

**Issue by ayaotz233** [haxibiao/youjianqi#8]
网页编辑文章时，添加外链图片的UI太过简陋，建议做一下基础美化（外框线对其等）。

**Comment by xiaoyunhuai** [comment]
这个我不会呀，算是小问题，你先用着，之后在优化吧！

**Comment by ivanzhang2** [comment]
这个问题，李梅找到simditor.js 的 代码，找到ImageButton 那个类的代码， 在init 还是某个函数里有如何渲染那个图片尺寸的 html代码， 把最下面的宽和高的输入部分，拿掉即可

**Comment by xiaoyunhuai** [comment]
这个已经完成，忘记说了

**Comment by ayaotz233** [comment]
我确认过了，没有问题
